"""rendering.py — the render-path hardening pins (09 §3 W-1/W-9; 10 §1
"Rendering" row): every markdown render (records, rationale, pane text,
page AND SSE frame alike) goes through :func:`render_markdown`, which is
constructed with ``html=False`` — markdown-it-py's DEFAULT preset passes
raw HTML through (empirically confirmed, see the module-level assertion
below and 09 §3's own citation of this fact); this module's whole reason
to exist is making that mistake structurally impossible to reach from
routes.py.

Diffs and proposal YAML render via Pygments in **class mode** (a served
stylesheet, never ``noclasses`` inline styles — W-9: a ``noclasses``
regression ships safe-but-unstyled under the CSP's ``style-src 'self'``,
silently dropping every ``style=""`` span). :func:`pygments_stylesheet`
is the one source of that served CSS — ``static/pygments.css`` is
generated from it once (a checked-in file, not regenerated per-request,
matching the vendored-htmx posture: no request-time Pygments stylesheet
computation).
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

import markupsafe
from markdown_it import MarkdownIt
from pygments import highlight as _pygments_highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import BashLexer, DiffLexer, YamlLexer

__all__ = [
    "PYGMENTS_CSS_CLASS",
    "PREVIEW_HONESTY_CAPTION",
    "humanize_ts",
    "pygments_stylesheet",
    "render_bash",
    "render_diff",
    "render_markdown",
    "render_yaml",
]

PYGMENTS_CSS_CLASS = "highlight"

#: html=False EXPLICITLY — the default preset's html=True is the
#: vulnerability 09 §3 W-1 names by name. One module-level instance;
#: never constructed ad hoc elsewhere (a second construction site could
#: drift back to the dangerous default).
_MD = MarkdownIt("commonmark", {"html": False})
assert _MD.options["html"] is False, "markdown-it-py html=False pin regressed"

_FORMATTER = HtmlFormatter(cssclass=PYGMENTS_CSS_CLASS, nowrap=False)

#: Carried from 02 §4 — same wording models.py already exports (models.py
#: is U2 territory; this module renders, it never re-derives the string).
PREVIEW_HONESTY_CAPTION = (
    "compilers regenerate from the record at apply time — this preview is "
    "advisory"
)


def render_markdown(text: str) -> str:
    """Record bodies, proposal rationale, pane transcript blocks — every
    markdown-sourced string in the app, page and SSE frame alike. Raw HTML
    in *text* is escaped, never passed through (W-1)."""
    return _MD.render(text or "")


def render_diff(text: str) -> str:
    """Pygments ``DiffLexer``, class mode (W-9) — ``proposals/lrn-<id>.diff``."""
    return _pygments_highlight(text or "", DiffLexer(), _FORMATTER)


def render_yaml(text: str) -> str:
    """Pygments YAML lexer, class mode — the raw proposal sibling text
    when no ``.diff`` exists (09 §2.3)."""
    return _pygments_highlight(text or "", YamlLexer(), _FORMATTER)


def render_bash(text: str) -> str:
    """Pygments bash lexer, class mode — a hook proposal's FULL stored
    script (09 §11 Y-7: "renders its entire stored script")."""
    return _pygments_highlight(text or "", BashLexer(), _FORMATTER)


#: The two pygments themes the served stylesheet carries (Y-10: dark is
#: the standing user theme; the shipped v1 file was light-only, which
#: rendered the Change previews light-gray-on-white in dark mode —
#: ui-polish pass, 2026-07-17).
_PYGMENTS_LIGHT_STYLE = "default"
_PYGMENTS_DARK_STYLE = "github-dark"

_STYLESHEET_HEADER = f"""\
/* pygments.css — GENERATED by self_learn_ui.rendering.pygments_stylesheet()
   (class mode, 09 §3 CSP pin: never noclasses). Do not hand-edit — the
   test suite pins this file byte-for-byte to the generator. Light theme
   = "{_PYGMENTS_LIGHT_STYLE}", dark theme = "{_PYGMENTS_DARK_STYLE}",
   scoped under prefers-color-scheme so Change previews stay legible in
   BOTH themes. Backgrounds/borders come from style.css's .highlight
   rules — token colors only here. */
"""


def _theme_defs(style: str) -> str:
    """One theme's token defs, minus its surface *background*: style.css
    owns preview surfaces in both themes, but every non-background
    declaration on the theme's own ``.highlight`` rule (github-dark also
    sets its default foreground there) is preserved — dropping the whole
    line silently discarded the dark default ``color`` (adversarial
    review 2026-07-17, finding #2)."""
    formatter = HtmlFormatter(cssclass=PYGMENTS_CSS_CLASS, style=style)
    prefix = f".{PYGMENTS_CSS_CLASS} {{"
    out: list[str] = []
    for line in formatter.get_style_defs(f".{PYGMENTS_CSS_CLASS}").splitlines():
        if line.startswith(prefix):
            body = line[len(prefix):].rsplit("}", 1)[0]
            kept = [
                d.strip()
                for d in body.split(";")
                if d.strip() and not d.strip().startswith("background")
            ]
            if kept:
                out.append(f"{prefix} {'; '.join(kept)} }}")
            continue
        out.append(line)
    return "\n".join(out)


def pygments_stylesheet() -> str:
    """The served stylesheet class-mode rendering depends on (W-9). Used
    to (re)generate the checked-in ``static/pygments.css`` — not called
    per-request in the running app. Emits BOTH themes: light defs at top
    level, dark defs inside a ``prefers-color-scheme: dark`` block."""
    dark = "\n".join(f"  {line}" if line else "" for line in _theme_defs(_PYGMENTS_DARK_STYLE).splitlines())
    return (
        f"{_STYLESHEET_HEADER}\n"
        f"{_theme_defs(_PYGMENTS_LIGHT_STYLE)}\n\n"
        f"@media (prefers-color-scheme: dark) {{\n{dark}\n}}\n"
    )


# ------------------------------------------------------------ humanize_ts

#: F5-6 (feedback round 5, U19 §1.4): the pinned bucket boundaries, in
#: seconds/days — every raw ISO-8601 timestamp a human reads (Detail's
#: finding line, Front's miner block, follow-ups, report.html) renders
#: through this ONE filter. Server-rendered only: `now` defaults to the
#: server's own clock at render time, never a client-side computation —
#: a stale relative label simply refreshes with the next page load.
_JUST_NOW_SECONDS = 90
_SECONDS_PER_MINUTE = 60
_SECONDS_PER_HOUR = 3600
_SECONDS_PER_DAY = 86400
_MONTH_CUTOFF_DAYS = 14


def humanize_ts(value: Any, *, now: datetime | None = None) -> str:
    """Relative plain words for a raw ISO-8601 string, with the exact
    instant preserved in a ``title`` attribute (hover reveals it) —
    registered as the Jinja filter of the same name (wrapped in
    ``markupsafe.Markup`` at registration, :mod:`self_learn_ui.app`, the
    same pattern as every other HTML-emitting filter here). Pinned
    buckets: "just now" (<90s), "N minutes ago", "N hours ago",
    "yesterday", "N days ago", "Mon DD" (>=14 days, current year),
    "Mon DD, YYYY" (older). A FUTURE instant (``unblocks_on`` is
    routinely one) skips the past-tense "ago"/"yesterday" wording
    entirely — direction-neutral "Mon DD"/"Mon DD, YYYY" either way, so
    it never claims a wrong direction. Anything that isn't a non-empty
    string, or doesn't parse as ISO-8601, renders the ORIGINAL value
    verbatim — never a crash, never a blank cell (the garbage-passthrough
    pin)."""
    if not value or not isinstance(value, str):
        return ""
    try:
        parsed = _parse_iso(value)
    except (ValueError, TypeError):
        return _wrap(value, value)
    reference = now if now is not None else datetime.now(timezone.utc)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    seconds = (reference - parsed).total_seconds()
    if seconds < 0:
        return _wrap(_absolute_date_words(parsed, reference), value)
    return _wrap(_bucket_words(parsed, reference, seconds), value)


def _parse_iso(value: str) -> datetime:
    # A bare "Z" UTC suffix (every timestamp this codebase writes) isn't
    # accepted by fromisoformat on the Python versions this project still
    # supports — normalize it to the offset form, the same tolerant read
    # every other ISO parse in this codebase does.
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def _bucket_words(parsed: datetime, reference: datetime, seconds: float) -> str:
    if seconds < _JUST_NOW_SECONDS:
        return "just now"
    if seconds < _SECONDS_PER_HOUR:
        minutes = int(seconds // _SECONDS_PER_MINUTE)
        return f"{minutes} minute{'s' if minutes != 1 else ''} ago"
    if seconds < _SECONDS_PER_DAY:
        hours = int(seconds // _SECONDS_PER_HOUR)
        return f"{hours} hour{'s' if hours != 1 else ''} ago"
    days = int(seconds // _SECONDS_PER_DAY)
    if days == 1:
        return "yesterday"
    if days < _MONTH_CUTOFF_DAYS:
        return f"{days} days ago"
    return _absolute_date_words(parsed, reference)


def _absolute_date_words(parsed: datetime, reference: datetime) -> str:
    if parsed.year == reference.year:
        return parsed.strftime("%b %d")
    return parsed.strftime("%b %d, %Y")


def _wrap(words: str, iso: str) -> str:
    return f'<span title="{markupsafe.escape(iso)}">{markupsafe.escape(words)}</span>'
